# Generated by Django 3.1.4 on 2021-06-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0008_auto_20210313_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmenttime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
